global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#dmitriy_vtulkin'
